In [1]:
import pandas as pd
import numpy as np
import os
from pprint import pprint

In [2]:
path_to_raw_data = os.path.join('..', 'raw_data', 'epci')
print(path_to_raw_data)

../raw_data/epci

In [3]:
list_of_files = sorted(os.listdir(path_to_raw_data))
pprint(list_of_files)

['Intercommunalite-Metropole_au_01-01-2020_v1.xlsx',
 'Intercommunalite_Metropole_au_01-01-2016.xls',
 'Intercommunalite_Metropole_au_01-01-2017.xls',
 'Intercommunalite_Metropole_au_01-01-2018.xls',
 'Intercommunalite_Metropole_au_01-01-2019.xls']

## Traitement des données de 2016

> Les communautés urbaines (CU), communautés d'agglomération (CA), communautés de communes (CC), syndicats d'agglomération nouvelle (SA), et  métropoles (ME) sont les EPCI à fiscalité propre retenus ici.

In [4]:
liste_epci = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[1]),
    sheet_name='Liste_des_EPCI',
    skiprows=5,
#     engine='openpyxl',
)

liste_epci.head()

        EPCI                                     LIBEPCI NATURE_EPCI  NB_COM
0  200000164                                 CC de Pange          CC      18
1  200000172                         CC Faucigny-Glières          CC       7
2  200000354                  CC de la Louge et du Touch          CC      14
3  200000388                            CC du Sud Morvan          CC       7
4  200000420  CC de la Vôge vers les Rives de la Moselle          CC      11

In [5]:

liste_epci.tail()

,EPCI,LIBEPCI,NATURE_EPCI,NB_COM
2059,249740101,CA Territoire de la Côte Ouest (Tco),CA,5
2060,249740119,CA Intercommunale du Nord de la Réunion (Cinor),CA,3
2061,251000832,CC Seine Barse,CC,13
2062,256500612,CC du Pays Toy,CC,15
2063,ZZZZZZZZZ,Sans objet,ZZ,27

In [6]:
composition_communale = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[1]),
    sheet_name='Composition_communale',
    skiprows=5,
#     engine='openpyxl',
)

In [7]:
composition_communale.head()

,CODGEO,LIBGEO,EPCI,LIBEPCI,DEP,REG
0,01001,L'Abergement-Clémenciat,200035210,CC Chalaronne Centre,01,84
1,01002,L'Abergement-de-Varey,240100883,CC de la Plaine de l'Ain,01,84
2,01004,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,01,84
3,01005,Ambérieux-en-Dombes,200042497,CC Dombes Saône Vallée,01,84
4,01006,Ambléon,200040350,CC Bugey Sud,01,84

In [8]:
liste_epci.tail()

,EPCI,LIBEPCI,NATURE_EPCI,NB_COM
2059,249740101,CA Territoire de la Côte Ouest (Tco),CA,5
2060,249740119,CA Intercommunale du Nord de la Réunion (Cinor),CA,3
2061,251000832,CC Seine Barse,CC,13
2062,256500612,CC du Pays Toy,CC,15
2063,ZZZZZZZZZ,Sans objet,ZZ,27

In [9]:
liste_epci.columns = [
    'code_epci', 
    'libelle_epci',
    'nature_epci',
    'nb_communes'
]

In [10]:
len(composition_communale)

35885

In [11]:
composition_communale.head()

,CODGEO,LIBGEO,EPCI,LIBEPCI,DEP,REG
0,01001,L'Abergement-Clémenciat,200035210,CC Chalaronne Centre,01,84
1,01002,L'Abergement-de-Varey,240100883,CC de la Plaine de l'Ain,01,84
2,01004,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,01,84
3,01005,Ambérieux-en-Dombes,200042497,CC Dombes Saône Vallée,01,84
4,01006,Ambléon,200040350,CC Bugey Sud,01,84

In [12]:
composition_communale.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35885 entries, 0 to 35884
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CODGEO   35885 non-null  object
 1   LIBGEO   35885 non-null  object
 2   EPCI     35885 non-null  object
 3   LIBEPCI  35885 non-null  object
 4   DEP      35885 non-null  object
 5   REG      35885 non-null  int64
dtypes: int64(1), object(5)
memory usage: 1.6+ MB

In [13]:
composition_communale.columns = [
    'codgeo',
    'libgeo',
    'code_epci',
    'libelle_epci',
    'code_departement',
    'code_region'
]

In [14]:
df = pd.merge(
    left=composition_communale,
    right=liste_epci,
    how='inner',
    on=['code_epci', 'libelle_epci']
)

In [15]:
df.shape

(35885, 8)

In [16]:
df.isna().sum()

codgeo              0
libgeo              0
code_epci           0
libelle_epci        0
code_departement    0
code_region         0
nature_epci         0
nb_communes         0
dtype: int64

In [17]:
df.head()

,codgeo,libgeo,code_epci,libelle_epci,code_departement,code_region,nature_epci,nb_communes
0,01001,L'Abergement-Clémenciat,200035210,CC Chalaronne Centre,01,84,CC,15
1,01028,Baneins,200035210,CC Chalaronne Centre,01,84,CC,15
2,01083,Chaneins,200035210,CC Chalaronne Centre,01,84,CC,15
3,01093,Châtillon-sur-Chalaronne,200035210,CC Chalaronne Centre,01,84,CC,15
4,01113,Condeissiat,200035210,CC Chalaronne Centre,01,84,CC,15

In [18]:
verif1 = df.groupby(['code_epci']).count()['nb_communes'].reset_index()
verif1.head()

   code_epci  nb_communes
0  200000164           18
1  200000172            7
2  200000354           14
3  200000388            7
4  200000420           11

In [19]:
verif2 = pd.merge(left=verif1, right=liste_epci, how='outer')

verif2

,code_epci,nb_communes,libelle_epci,nature_epci
0,200000164,18,CC de Pange,CC
1,200000172,7,CC Faucigny-Glières,CC
2,200000354,14,CC de la Louge et du Touch,CC
3,200000388,7,CC du Sud Morvan,CC
4,200000420,11,CC de la Vôge vers les Rives de la Moselle,CC
...,...,...,...,...
2059,249740101,5,CA Territoire de la Côte Ouest (Tco),CA
2060,249740119,3,CA Intercommunale du Nord de la Réunion (Cinor),CA
2061,251000832,13,CC Seine Barse,CC
2062,256500612,15,CC du Pays Toy,CC
2063,ZZZZZZZZZ,27,Sans objet,ZZ

In [20]:
verif1.shape

(2064, 2)

In [21]:
liste_epci.shape

(2064, 4)

In [22]:
liste_epci

,code_epci,libelle_epci,nature_epci,nb_communes
0,200000164,CC de Pange,CC,18
1,200000172,CC Faucigny-Glières,CC,7
2,200000354,CC de la Louge et du Touch,CC,14
3,200000388,CC du Sud Morvan,CC,7
4,200000420,CC de la Vôge vers les Rives de la Moselle,CC,11
...,...,...,...,...
2059,249740101,CA Territoire de la Côte Ouest (Tco),CA,5
2060,249740119,CA Intercommunale du Nord de la Réunion (Cinor),CA,3
2061,251000832,CC Seine Barse,CC,13
2062,256500612,CC du Pays Toy,CC,15
2063,ZZZZZZZZZ,Sans objet,ZZ,27

In [23]:
df.head()

,codgeo,libgeo,code_epci,libelle_epci,code_departement,code_region,nature_epci,nb_communes
0,01001,L'Abergement-Clémenciat,200035210,CC Chalaronne Centre,01,84,CC,15
1,01028,Baneins,200035210,CC Chalaronne Centre,01,84,CC,15
2,01083,Chaneins,200035210,CC Chalaronne Centre,01,84,CC,15
3,01093,Châtillon-sur-Chalaronne,200035210,CC Chalaronne Centre,01,84,CC,15
4,01113,Condeissiat,200035210,CC Chalaronne Centre,01,84,CC,15

In [24]:
df.to_csv(
    os.path.join(
        '..',
        'clean_data',
        'epci',
        '2016.csv'
    ),
    index=False
)

## Traitement des données de 2017

In [25]:
pprint(list_of_files)

['Intercommunalite-Metropole_au_01-01-2020_v1.xlsx',
 'Intercommunalite_Metropole_au_01-01-2016.xls',
 'Intercommunalite_Metropole_au_01-01-2017.xls',
 'Intercommunalite_Metropole_au_01-01-2018.xls',
 'Intercommunalite_Metropole_au_01-01-2019.xls']

In [26]:
liste_epci = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[2]),
    sheet_name='EPCI',
    skiprows=5,
#     engine='openpyxl',
)

liste_epci.columns = [
    'code_epci', 
    'libelle_epci',
    'nature_epci',
    'nb_communes'
]

liste_epci.head()

,code_epci,libelle_epci,nature_epci,nb_communes
0,200000172,CC Faucigny-Glières,CC,7
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,CC,9
2,200000545,CC des Portes de Romilly-sur-Seine,CC,6
3,200000628,CC Rhône Lez Provence,CC,5
4,200000800,CC Coeur de Sologne,CC,6

In [27]:
liste_epci.tail()

,code_epci,libelle_epci,nature_epci,nb_communes
1263,249740085,CA du Sud,CA,4
1264,249740093,CA Intercommunale de la Réunion Est (Cirest),CA,6
1265,249740101,CA Territoire de la Côte Ouest (Tco),CA,5
1266,249740119,CA Intercommunale du Nord de la Réunion (Cinor),CA,3
1267,ZZZZZZZZZ,Sans objet,ZZ,5

In [28]:
composition_communale = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[2]),
    sheet_name='Composition_communale',
    skiprows=5,
#     engine='openpyxl',
)

composition_communale.head()

,CODGEO,LIBGEO,EPCI,LIBEPCI,DEP,REG
0,01001,L'Abergement-Clémenciat,200069193,CC de la Dombes,01,84
1,01002,L'Abergement-de-Varey,240100883,CC de la Plaine de l'Ain,01,84
2,01004,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,01,84
3,01005,Ambérieux-en-Dombes,200042497,CC Dombes Saône Vallée,01,84
4,01006,Ambléon,200040350,CC Bugey Sud,01,84

In [29]:
composition_communale.tail()

      CODGEO         LIBGEO       EPCI             LIBEPCI  DEP  REG
35411  97613  M'Tsangamouji  200059871  CC du Centre-Ouest  976    6
35412  97614       Ouangani  200059871  CC du Centre-Ouest  976    6
35413  97615       Pamandzi  200050532  CC de Petite-Terre  976    6
35414  97616           Sada  200059871  CC du Centre-Ouest  976    6
35415  97617       Tsingoni  200059871  CC du Centre-Ouest  976    6

In [30]:
composition_communale.columns = [
    'codgeo',
    'libgeo',
    'code_epci',
    'libelle_epci',
    'code_departement',
    'code_region'
]

In [31]:
df = pd.merge(
    left=liste_epci,
    right=composition_communale,
    how='inner',
    on=['libelle_epci', 'code_epci']
)

df.head()

,code_epci,libelle_epci,nature_epci,nb_communes,codgeo,libgeo,code_departement,code_region
0,200000172,CC Faucigny-Glières,CC,7,74024,Ayse,74,84
1,200000172,CC Faucigny-Glières,CC,7,74042,Bonneville,74,84
2,200000172,CC Faucigny-Glières,CC,7,74049,Brizon,74,84
3,200000172,CC Faucigny-Glières,CC,7,74087,Contamine-sur-Arve,74,84
4,200000172,CC Faucigny-Glières,CC,7,74164,Marignier,74,84

In [32]:
df.shape

(35416, 8)

In [33]:
composition_communale.shape

(35416, 6)

In [34]:
df.to_csv(
    os.path.join(
        '..',
        'clean_data',
        'epci',
        '2017.csv'
    ),
    index=False
)

## Traitement des données de 2018

In [35]:
pprint(list_of_files)

['Intercommunalite-Metropole_au_01-01-2020_v1.xlsx',
 'Intercommunalite_Metropole_au_01-01-2016.xls',
 'Intercommunalite_Metropole_au_01-01-2017.xls',
 'Intercommunalite_Metropole_au_01-01-2018.xls',
 'Intercommunalite_Metropole_au_01-01-2019.xls']

In [36]:
liste_epci = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[3]),
    sheet_name='EPCI',
    skiprows=5,
#     engine='openpyxl',
)

liste_epci.columns = [
    'code_epci', 
    'libelle_epci',
    'nature_epci',
    'nb_communes'
]

liste_epci.head()

,code_epci,libelle_epci,nature_epci,nb_communes
0,200000172,CC Faucigny-Glières,CC,7
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,CC,9
2,200000545,CC des Portes de Romilly-sur-Seine,CC,6
3,200000628,CC Rhône Lez Provence,CC,5
4,200000800,CC Coeur de Sologne,CC,6

In [37]:
liste_epci.tail()

,code_epci,libelle_epci,nature_epci,nb_communes
1260,249740085,CA du Sud,CA,4
1261,249740093,CA Intercommunale de la Réunion Est (Cirest),CA,6
1262,249740101,CA Territoire de la Côte Ouest (Tco),CA,5
1263,249740119,CA Intercommunale du Nord de la Réunion (Cinor),CA,3
1264,ZZZZZZZZZ,Sans objet,ZZ,4

In [38]:
composition_communale = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[3]),
    sheet_name='Composition_communale',
    skiprows=5,
#     engine='openpyxl',
)

composition_communale.head()

,CODGEO,LIBGEO,EPCI,LIBEPCI,DEP,REG
0,01001,L'Abergement-Clémenciat,200069193,CC de la Dombes,01,84
1,01002,L'Abergement-de-Varey,240100883,CC de la Plaine de l'Ain,01,84
2,01004,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,01,84
3,01005,Ambérieux-en-Dombes,200042497,CC Dombes Saône Vallée,01,84
4,01006,Ambléon,200040350,CC Bugey Sud,01,84

In [39]:
composition_communale.tail()

      CODGEO         LIBGEO       EPCI             LIBEPCI  DEP  REG
35352  97613  M'Tsangamouji  200059871  CC du Centre-Ouest  976    6
35353  97614       Ouangani  200059871  CC du Centre-Ouest  976    6
35354  97615       Pamandzi  200050532  CC de Petite-Terre  976    6
35355  97616           Sada  200059871  CC du Centre-Ouest  976    6
35356  97617       Tsingoni  200059871  CC du Centre-Ouest  976    6

In [40]:
composition_communale.columns = [
    'codgeo',
    'libgeo',
    'code_epci',
    'libelle_epci',
    'code_departement',
    'code_region'
]

In [41]:
df = pd.merge(
    left=liste_epci,
    right=composition_communale,
    how='inner',
    on=['libelle_epci', 'code_epci']
)

df.head()

,code_epci,libelle_epci,nature_epci,nb_communes,codgeo,libgeo,code_departement,code_region
0,200000172,CC Faucigny-Glières,CC,7,74024,Ayse,74,84
1,200000172,CC Faucigny-Glières,CC,7,74042,Bonneville,74,84
2,200000172,CC Faucigny-Glières,CC,7,74049,Brizon,74,84
3,200000172,CC Faucigny-Glières,CC,7,74087,Contamine-sur-Arve,74,84
4,200000172,CC Faucigny-Glières,CC,7,74164,Marignier,74,84

In [42]:
df.shape

(35357, 8)

In [43]:
composition_communale.shape

(35357, 6)

In [44]:
df.to_csv(
    os.path.join(
        '..',
        'clean_data',
        'epci',
        '2018.csv'
    ),
    index=False
)

## Traitement des données de 2019

In [45]:
pprint(list_of_files)

['Intercommunalite-Metropole_au_01-01-2020_v1.xlsx',
 'Intercommunalite_Metropole_au_01-01-2016.xls',
 'Intercommunalite_Metropole_au_01-01-2017.xls',
 'Intercommunalite_Metropole_au_01-01-2018.xls',
 'Intercommunalite_Metropole_au_01-01-2019.xls']

In [46]:
liste_epci = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[4]),
    sheet_name='EPCI',
    skiprows=5,
#     engine='openpyxl',
)

liste_epci.columns = [
    'code_epci', 
    'libelle_epci',
    'nature_epci',
    'nb_communes'
]

liste_epci.head()

,code_epci,libelle_epci,nature_epci,nb_communes
0,200000172,CC Faucigny-Glières,CC,7
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,CC,9
2,200000545,CC des Portes de Romilly-sur-Seine,CC,6
3,200000628,CC Rhône Lez Provence,CC,5
4,200000800,CC Coeur de Sologne,CC,6

In [47]:
liste_epci.tail()

,code_epci,libelle_epci,nature_epci,nb_communes
1255,249740085,CA du Sud,CA,4
1256,249740093,CA Intercommunale de la Réunion Est (CIREST),CA,6
1257,249740101,CA Territoire de la Côte Ouest (TCO),CA,5
1258,249740119,CA Intercommunale du Nord de la Réunion (CINOR),CA,3
1259,ZZZZZZZZZ,Sans objet,ZZ,4

In [48]:
composition_communale = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[4]),
    sheet_name='Composition_communale',
    skiprows=5,
#     engine='openpyxl',
)

composition_communale.head()

,CODGEO,LIBGEO,EPCI,LIBEPCI,DEP,REG
0,01001,L'Abergement-Clémenciat,200069193,CC de la Dombes,01,84
1,01002,L'Abergement-de-Varey,240100883,CC de la Plaine de l'Ain,01,84
2,01004,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,01,84
3,01005,Ambérieux-en-Dombes,200042497,CC Dombes Saône Vallée,01,84
4,01006,Ambléon,200040350,CC Bugey Sud,01,84

In [49]:
composition_communale.tail()

      CODGEO         LIBGEO       EPCI             LIBEPCI  DEP  REG
34965  97613  M'Tsangamouji  200059871  CC du Centre-Ouest  976    6
34966  97614       Ouangani  200059871  CC du Centre-Ouest  976    6
34967  97615       Pamandzi  200050532  CC de Petite-Terre  976    6
34968  97616           Sada  200059871  CC du Centre-Ouest  976    6
34969  97617       Tsingoni  200059871  CC du Centre-Ouest  976    6

In [50]:
composition_communale.columns = [
    'codgeo',
    'libgeo',
    'code_epci',
    'libelle_epci',
    'code_departement',
    'code_region'
]

In [51]:
df = pd.merge(
    left=liste_epci,
    right=composition_communale,
    how='inner',
    on=['libelle_epci', 'code_epci']
)

df.head()

,code_epci,libelle_epci,nature_epci,nb_communes,codgeo,libgeo,code_departement,code_region
0,200000172,CC Faucigny-Glières,CC,7,74024,Ayse,74,84
1,200000172,CC Faucigny-Glières,CC,7,74042,Bonneville,74,84
2,200000172,CC Faucigny-Glières,CC,7,74049,Brizon,74,84
3,200000172,CC Faucigny-Glières,CC,7,74087,Contamine-sur-Arve,74,84
4,200000172,CC Faucigny-Glières,CC,7,74164,Marignier,74,84

In [52]:
df.shape

(34970, 8)

In [53]:
composition_communale.shape

(34970, 6)

In [54]:
df.to_csv(
    os.path.join(
        '..',
        'clean_data',
        'epci',
        '2019.csv'
    ),
    index=False
)

## Traitement des données de 2020

In [55]:
pprint(list_of_files)

['Intercommunalite-Metropole_au_01-01-2020_v1.xlsx',
 'Intercommunalite_Metropole_au_01-01-2016.xls',
 'Intercommunalite_Metropole_au_01-01-2017.xls',
 'Intercommunalite_Metropole_au_01-01-2018.xls',
 'Intercommunalite_Metropole_au_01-01-2019.xls']

In [56]:
liste_epci = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[0]),
    sheet_name='EPCI',
    skiprows=5,
    engine='openpyxl',
)

liste_epci.columns = [
    'code_epci', 
    'libelle_epci',
    'nature_epci',
    'nb_communes'
]

liste_epci.head()

,code_epci,libelle_epci,nature_epci,nb_communes
0,200000172,CC Faucigny-Glières,CC,7
1,200000438,CC du Pays de Pontchâteau Saint-Gildas-des-Bois,CC,9
2,200000545,CC des Portes de Romilly-sur-Seine,CC,6
3,200000628,CC Rhône Lez Provence,CC,5
4,200000800,CC Cœur de Sologne,CC,6

In [57]:
liste_epci.tail()

,code_epci,libelle_epci,nature_epci,nb_communes
1251,249740085,CA du Sud,CA,4
1252,249740093,CA Intercommunale de la Réunion Est (CIREST),CA,6
1253,249740101,CA Territoire de la Côte Ouest (TCO),CA,5
1254,249740119,CA Intercommunale du Nord de la Réunion (CINOR),CA,3
1255,ZZZZZZZZZ,Sans objet,ZZ,4

In [58]:
composition_communale = pd.read_excel(
    os.path.join(path_to_raw_data, list_of_files[0]),
    sheet_name='Composition_communale',
    skiprows=5,
    engine='openpyxl',
)

composition_communale.head()

,CODGEO,LIBGEO,EPCI,LIBEPCI,DEP,REG
0,01001,L'Abergement-Clémenciat,200069193,CC de la Dombes,01,84
1,01002,L'Abergement-de-Varey,240100883,CC de la Plaine de l'Ain,01,84
2,01004,Ambérieu-en-Bugey,240100883,CC de la Plaine de l'Ain,01,84
3,01005,Ambérieux-en-Dombes,200042497,CC Dombes Saône Vallée,01,84
4,01006,Ambléon,200040350,CC Bugey Sud,01,84

In [59]:
composition_communale.tail()

      CODGEO         LIBGEO       EPCI             LIBEPCI  DEP  REG
34963  97613  M'Tsangamouji  200059871  CC du Centre-Ouest  976    6
34964  97614       Ouangani  200059871  CC du Centre-Ouest  976    6
34965  97615       Pamandzi  200050532  CC de Petite-Terre  976    6
34966  97616           Sada  200059871  CC du Centre-Ouest  976    6
34967  97617       Tsingoni  200059871  CC du Centre-Ouest  976    6

In [60]:
composition_communale.columns = [
    'codgeo',
    'libgeo',
    'code_epci',
    'libelle_epci',
    'code_departement',
    'code_region'
]

In [61]:
df = pd.merge(
    left=liste_epci,
    right=composition_communale,
    how='inner',
    on=['libelle_epci', 'code_epci']
)

df.head()

,code_epci,libelle_epci,nature_epci,nb_communes,codgeo,libgeo,code_departement,code_region
0,200000172,CC Faucigny-Glières,CC,7,74024,Ayse,74,84
1,200000172,CC Faucigny-Glières,CC,7,74042,Bonneville,74,84
2,200000172,CC Faucigny-Glières,CC,7,74049,Brizon,74,84
3,200000172,CC Faucigny-Glières,CC,7,74087,Contamine-sur-Arve,74,84
4,200000172,CC Faucigny-Glières,CC,7,74164,Marignier,74,84

In [62]:
df.shape

(34968, 8)

In [63]:
composition_communale.shape

(34968, 6)

In [64]:
df.to_csv(
    os.path.join(
        '..',
        'clean_data',
        'epci',
        '2020.csv'
    ),
    index=False
)